apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weft-operator.serviceAccountName" . }}
  labels:
    {{- include "weft-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.create }}
{{- end }}
